# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApi', '0002_productratedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='productratedetail',
            name='doc_url',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='productratedetail',
            name='pic_url',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
