# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApi', '0003_auto_20170516_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('products', models.ManyToManyField(to='myApi.ProductRateDetail')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
