# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApi', '0006_auto_20170517_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='data_input',
            field=models.TextField(null=True),
        ),
    ]
