# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApi', '0007_project_data_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='productratedetail',
            name='algorithm',
            field=models.IntegerField(null=True),
        ),
    ]
